### ISSUE TITLE
Cessan 172 G1000 Profile: Camera Buttons not working

### ISSUE THREAD

**Issue by mariokoehler** [flightdeck-to/msfs2020#1]
I noticed that on my system all the camera buttons don't work.

For example the "PILOT" button in the lower row, second from the left. I can see in the stream deck app that it is bound to the hotkey "F". If i press "F" manually while in MSFS, it works and the view changes to pilot. but if i press the stream deck button, nothing happens.

next thing i tried was to open notepad, place the cursor in it and press the stream deck button, and surprisingly it works...a lower case "f" shows up.

So for some reason stream deck does send the keystroke, but it's not recognized by MSFS.

Don't know if you can do anything about it, since the "hotkey"-action is not even a stream deck action from your plugin, but i figured you would at least be interested to know. Maybe i'm not the only one with the effect, we'll see.

By the way...the other stream deck buttons seem to work fine, autopilot, lights, flaps...tested all that and works ok. but i believe they are actions from your plugin that communicate via simconnect and not keypresses.

I know from personal experience, from doing some "botting" of other games with AutoIt, that some games are "finnicky" in terms of the way you need to send keystrokes, so i suspect its something along those lines.

I'm on a german Windows so it could be some language setting, too.

If i find something out or get it working, i'll let you know.

**Comment by mariokoehler** [comment]
i just did another test, i created a stream deck button that is linked to the hotkey "1" and then i opened the "fuel & weights" dialog, clicked into the cargo input field and pressed the stream deck button: nothing. does not work, the "1" is not recognized. so the "hotkey"-action is not working at all for me it seems.

**Comment by flightdeck-to** [comment]
Sorry to hear that the hotkeys are not working, the camera buttons are indeed linked to hotkeys at this moment. I keep a close eye on every SDK update but at this moment the SDK does not support SimConnect camera commands.

Is MSFS in focus when you try to change the camera view (click in the MSFS window once with your mouse to make sure it's in focus?

**Comment by mariokoehler** [comment]
i got it working. i needed to start the StreamDeck application with admin permissions (right click windows shortcut, properties, advanced, run as administrator). after that it works fine. I found the hint while googling, seems to be a common problem.

but it's maybe something you could include in your readme or FAQ or something like that as a suggestion if people run into this problem.

best regards
Mario

P.S.: enjoying your product so far!

**Comment by flightdeck-to** [comment]
I updated the F.A.Q. straight away, thank you for figuring this out, are you using the Microsoft Store, Steam or boxed edition?

**Comment by mariokoehler** [comment]
i'm using the Steam Edition.

**Comment by flightdeck-to** [comment]
That's unfortunate, me and my friends use the Steam version as well but do not experience that Stream Deck had to run in Administrator mode, I had a slight hope it was something occurring with a specific version :(. I'll try to change my Windows version to German, see if that makes a difference. My rational mind says, it can't be that, but it's still Microsoft, so you never know ;).

**Comment by mariokoehler** [comment]
I noticed that my FlightSimulator.exe also has the flag set to be run in admin mode (you could compare that with your installation, maybe yours is not running as admin?). 

I didn't set that flag myself, it was done during the installation i assume. I can imagine that because FS was running in admin mode but stream deck did not, there is some kind of weird microsoft security layer in the background that limits the way the non-admin app can influence the admin app.

**Comment by mariokoehler** [comment]
oh and i agree...i don't think its the german setting either...that would be a very weird connection
