### ISSUE TITLE
Toggle values G1000_PFD_ENTER_BUTTON and G1000_PFD_SOFTKEY don't seem to be recognized

### ISSUE THREAD

**Issue by mariokoehler** [flightdeck-to/msfs2020#2]
I tried building a page to modify the ADF frequency, because thats always fiddely as fuck with the mouse controls :-)

I got the increase/decrease buttons for the 1/10/100 digits working, using the toggle values ADF_100_INC, ADF_10_INC, ADF_1_INC, ADF_100_DEC, ADF_10_DEC and ADF_1_DEC. But to swap the frequency from standby to active you have to press the ENTER button on the G1000.

I tried both G1000_PFD_ENTER_BUTTON and G1000_MFD_ENTER_BUTTON as toggle values, but they don't seem to do anything.

Same problem with the G1000_PFD_SOFTKEY1 to G1000_PFD_SOFTKEY12, they don't work either. I would have needed to use G1000_PFD_SOFTKEY7 to get to the G1000 menu where you can change the ADF frequency.

On every button i left everything other than the title and the toggle value empty, like the header (what is that about anyway?) and the feedback value.

regards
Mario

**Comment by flightdeck-to** [comment]
Hi Mario,

The only way I found to simulate the "enter" is to actually the corresponding SET event with the new frequency (ADF_SET, XPNDR_SET, COM_STBY_RADIO_SET, COM2_STBY_RADIO_SET, NAV1_STBY_SET, NAV2_STBY_SET). I've got this working in a local test version (you set the frequency first in StreamDeck and by pressing the virtual enter button on the streamdeck the frequency is actually set to the correct value in the sim) and you can expect this in one of the upcoming releases.

Regards,

Robbert

**Comment by mariokoehler** [comment]
sounds good, i'm looking forward to that.
