### ISSUE TITLE
Please state that the source code is from https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck

### ISSUE THREAD

**Issue by nguyenquyhy** [flightdeck-to/msfs2020#3]
Hi, this plugin is under GPL license. So you are free to use and modify, but please state in your README that this is a modified version of the original source from https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck.

**Comment by flightdeck-to** [comment]
I've added a modify.md where I credit your excellent work and state that this is a modification of that work. As you can see you and the other authors are also mentioned in the manifest.json of the Stream Deck plugin.
